images = [
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_1606.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_0897.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_1423.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_1454.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_1605.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_3944.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_3980.JPG")
  src(s0).out()
      },
  ()=>{s0.initImage("https://raw.githubusercontent.com/fnassar/live_coding_final/main/images/IMG_4162.JPG")
  src(s0).out()
      }
]
