images = [
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_1606.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_0897.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_1423.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_1454.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_1605.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_3944.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_3980.JPG")
    src(s0).out(o0)
},
  ()=>{
    s0.initImage("/Users/nyuad/Documents/GitHub/liveCoding/fatema/live_coding_final/images/IMG_4162.JPG"
    src(s0).out(o0)
)}
]
